apiVersion: v1
kind: Service
metadata:
  name: php-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  selector:
    app: php
  type: LoadBalancer
  loadBalancerIP: 192.168.99.127
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  labels:
    app: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: php_image
          imagePullPolicy: Never
          ports:
            - containerPort: 5000